// Module included in the following assemblies:
//
// * images/using_images/images-other-jenkins.adoc

[id="images-other-jenkins-oauth-auth_{context}"]
= {product-title} OAuth authentication

OAuth authentication is activated by configuring the *Configure Global Security*
panel in the Jenkins UI, or by setting the `OPENSHIFT_ENABLE_OAUTH` environment
variable on the Jenkins *Deployment configuration* to anything other than
`false`. This activates the OpenShift Login plug-in, which retrieves the
configuration information from pod data or by interacting with the
{product-title} API server.

Valid credentials are controlled by the {product-title} identity provider.
ifdef::openshift-enterprise,openshift-origin,openshift-dedicated[]
For example, if `Allow All` is the default identity provider, you can provide
any non-empty string for both the user name and password.
endif::[]

Jenkins supports both browser and non-browser access.

Valid users are automatically added to the Jenkins authorization matrix at log
in, where {product-title} *Roles* dictate the specific Jenkins permissions the
users have.

Users with the `admin` role have the traditional Jenkins administrative
user permissions. Users with the `edit` or `view` role have progressively
fewer permissions.

[NOTE]
====
The `admin` user that is pre-populated in the {product-title} Jenkins image with
administrative privileges is not given those privileges when
{product-title} OAuth is used, unless the {product-title} cluster administrator
explicitly defines that user in the {product-title} identity provider and
assigns the `admin` role to the user.
====

Jenkins' users permissions can be changed after the users are initially
established. The OpenShift Login plug-in polls the {product-title} API server
for permissions and updates the permissions stored in Jenkins for each user with
the permissions retrieved from {product-title}. If the Jenkins UI is used to
update permissions for a Jenkins user, the permission changes are overwritten
the next time the plug-in polls {product-title}.

You can control how often the polling occurs with the
`OPENSHIFT_PERMISSIONS_POLL_INTERVAL` environment variable. The default polling
interval is five minutes.

The easiest way to create a new Jenkins service using OAuth authentication is to
use a template.
