// Module included in the following assemblies:
//
// * images/using_images/images-other-jenkins-agent.adoc

[id="images-other-jenkins-agent-memory_{context}"]
= Jenkins agent memory requirements

A JVM is used in all Jenkins agents to host the Jenkins JNLP agent, as well as
to run any Java applications such as `javac`, Maven, or Gradle.

For memory efficiency, by default the Jenkins image dynamically uses a 32-bit
JVM if running in a container with a memory limit under 2GiB. The
JVM choice applies by default both for the Jenkins JNLP agent as well as for any
other Java processes within the agent container.

By default the Jenkins JNLP agent JVM uses 50% of the container memory limit for
its heap. This value can be modified by the `CONTAINER_HEAP_PERCENT`
environment variable. It can also be capped at an upper limit or overridden
entirely.

By default any other processes executed in the Jenkins agent container, such as
shell scripts or `oc` commands run from pipelines, may not be able to use more
than the remaining 50% memory limit without provoking an OOM kill.

By default, each further JVM process run in a Jenkins agent container will use
up to 25% of the container memory limit for their heap. It may be necessary to
tune this for many build workloads.
