[id="images-other-jenkins"]
= Configuring Jenkins images
include::modules/common-attributes.adoc[]
:context: images-other-jenkins
toc::[]

{product-title} provides a container image for running Jenkins. This image
provides a Jenkins server instance, which can be used to set up a basic flow for
continuous testing, integration, and delivery.

This image also includes a sample Jenkins job, which triggers a new build of a
*BuildConfig* defined in {product-title}, tests the output of that build, and
then on successful build, retags the output to indicate the build is ready for
production.

{product-title} follows the link:https://jenkins.io/changelog-stable/[LTS]
release of Jenkins. {product-title} provides an image containing Jenkins 2.x.

== Images

The {product-title} Jenkins image comes in two varieties:

*RHEL 7 Based Image*

The RHEL 7 image is available through the Red Hat Registry:

----
$ docker pull quay.io/openshift4/jenkins-2-rhel7
----

*CentOS 7 Based Image*

This image is available on Docker Hub:

----
$ docker pull openshift/jenkins-2-centos7
----

To use these images, you can either access them directly from these registries
or push them into your {product-title} container image registry. Additionally,
you can create an ImageStream that points to the image, either in your container
image registry or at the external location. Your {product-title} resources can
then reference the ImageStream.

== Configuration and customization

You can manage Jenkins authentication in two ways:

* {product-title} OAuth authentication provided by the OpenShift Login
plug-in.
* Standard authentication provided by Jenkins.

include::modules/images-other-jenkins-oauth-auth.adoc[leveloffset=+2]

include::modules/images-other-jenkins-auth.adoc[leveloffset=+2]

include::modules/images-other-jenkins-env-var.adoc[leveloffset=+1]

include::modules/images-other-jenkins-cross-project.adoc[leveloffset=+1]

== Jenkins cross volume mount points

The Jenkins image can be run with mounted volumes to enable persistent storage
for the configuration:

* *_/var/lib/jenkins_* - This is the data directory where Jenkins stores
configuration files including job definitions.

include::modules/images-other-jenkins-customize-s2i.adoc[leveloffset=+1]

include::modules/images-other-jenkins-config-kubernetes.adoc[leveloffset=+1]

include::modules/images-other-jenkins-permissions.adoc[leveloffset=+1]

include::modules/images-other-jenkins-create-service.adoc[leveloffset=+1]

include::modules/images-other-jenkins-kubernetes-plugin.adoc[leveloffset=+1]

include::modules/images-other-jenkins-memory.adoc[leveloffset=+1]
